# -*- coding: utf-8 -*-
"""AICapstone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ATDhH4hA3SsYPXU07RkH2wMwlQJWldID
"""



## import nltk
from tkinter import *
 
def send():
    send = "You -> " + e.get()
    txt.insert(END, "\n" + send)
 
    request = e.get().lower()
 
    response = chatbot.get_response(request)
    
    txt.insert(END, "\n" + "Bot -> ?" + str(response))
 


# GUI
root = Tk()
root.title("Chatbot")

BG_GRAY = "#ABB2B9"
BG_COLOR = "#17202A"
TEXT_COLOR = "#EAECEE"
 
FONT = "Helvetica 14"
FONT_BOLD = "Helvetica 13 bold"
lable1 = Label(root, bg=BG_COLOR, fg=TEXT_COLOR, text="AVA - administrative virtual assistant ", font=FONT_BOLD, pady=10, width=50, height=1).grid(
    row=0)
 
txt = Text(root, bg=BG_COLOR, fg=TEXT_COLOR, font=FONT, width=60)
txt.grid(row=1, column=0, columnspan=2)
 
scrollbar = Scrollbar(txt)
scrollbar.place(relheight=1, relx=0.974)
 
e = Entry(root, bg="#2C3E50", fg=TEXT_COLOR, font=FONT, width=55)
e.grid(row=2, column=0)
 




import logging #######'''''''''= logging.getLogger() logger.setLevel(logging.CRITICAL)

logger = logging.getLogger()

logger.setLevel(logging.CRITICAL)

from chatterbot import ChatBot

## import streamlit as st

from chatterbot.trainers import ListTrainer



## st.title("AVA- administrative virtual assistant")
## st.subheader("I can help you with your queries!")

chatbot= ChatBot('bot')

chatbot = ChatBot(
    'JARVIS',  
    logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.TimeLogicAdapter'], 
)

from chatterbot.trainers import ListTrainer
  
trainer = ListTrainer(chatbot)
  
trainer.train(
 
    [
 
    
 

    
    'What are the school timing?', 
    'It is from 8:15 to 2:15.',
'Is there ever stay back?',
'There may be stay back for sports or academics if the syllabus is not covered.',
'Do you offer any healthcare?',
'Once a year a health check up is conducted which is free of cost.',
'If a child were to be injured, what are the safety measures you have in place?',
'We have an infirmary with qualified staff, and if further medical attention is required we have an ambulance to transfer the child into a hospital.',
'Is uniform compulsory?',
'Yes it is and you can but it from the uniform store which is open during school hours.',
'How often are PTM’s conducted?',
'After every test conducted a PTM is scheduled to track the progress of the ward.',
'How many terms does the school have?',
'We conduct two terms, one before the Dussera break and one after.',
'Other than PTM when can a parent interact with the teacher?',
'The parents can always contact the teacher and set up a meeting at a comfortable hour.',

'What is the student teacher ratio?',
'The student teacher ratio is 35:1.',
'What are the marks of the toppers of class in 10/12 classes?',
'You can find this information on our home page.',
'Can the students choose their subjects?',
'Students can choose according to their eligibility and performance in the entrance test with a cutoff of 80 percent.',
'What are the different curriculums offered by the school?',
'We offer CBSE, IGCSE, IB and Kendra Vidyalay for government employees.',
'How often are extracurricular activities conducted in a week?',
'Everyday 1 period is devoted to the holistic development of the child.',
'How is technology integrated in the school?',
'Every classroom is installed with an operative educomp to help with better visualization of concepts, every block has a computer lap with fully functional computers.',
'Is AC available in the buses and classrooms?',
'No, the children are taught in fresh air.',
'Is lunch provided by the school?',
'It is not provided but you can always buy a nutritious meal in the canteen.',
'What are the timings of the uniform store?',
'It is open from 8:15 to 2:15 from Monday through Saturday.',


'What is the school average?'
'We always give the child opportunities to perform better hence no such average exists.',
'Can the fees be paid in installments?',
'Yes it can be paid in two installments online.',
'Is internship available?',
'There is no internship for the students, but we offer internships for other posts.',
'What are the actions taken to prevent bullying?',
'There is an anti bullying committee headed by the principle, there is an email id where you can file a complaint, and awareness programs are conducted.', 
'What are the actions taken for behavioral misconduct that may take place in school?',
'The child’s parents will be informed and the child will counseled.',
'What is the number of field trips offered by the school?',
'Every year two field trips are offered by the school.',
'Are the field trips outside the state/country?',
'We offer one trip that is outside the state and another one which is conducted outside the country.',
'Are there one day trips?',
'Yes, we do conduct educational one day trips.',
'Is the fees for the field trips conducted covered in the school fees?',
'No, this fee is not included in the school fees.',

'What are the different streams offered for 11th and 12 th?',
'We offer 22 options in science stream , 30 options in commerce and 23 options in humanities.',
'What are the steps taken if a child cannot keep up with the curriculum?',
'Parents and teachers are informed and remedials such as extra classes are conducted.',
'Is the school affiliated with any coaching institutes?',
'Yes it is integrated with ALLEN.',
'Will ID cards be provided?',
'Yes within the first month of the session ID cards will be provided.',
'Can the child be tracked while using the buses?',
'Yes using ENTRAR, the child can be monitored while using the buses.',
'Will there be an entrance test conducted?',
'For grades 5th and above an entrance test will conducted.',
'What is the cutoff for joining the school?',
'The child needs to score more than 50 percent on the test for admission.',
'Do they provide Letter of Recommendation?',
'Yes, according to how much the teachers know, a letter of recommendation will be drafted.',
'For students applying abroad, how will their predictive scores be analyzed?',
'Their predictive scores will be analyzed based on their 9th , 10th ad 11th marks.',

'What are the mediums provided by the school?',
'We offer only English medium.',
'Are scholarships provided for SCs and STs?',
'No, as we do not discriminate we do not offer special scholarships.',
'Are smart watches allowed?',
'No, they are not allowed.',
'What are the exceptions made for private transport students regarding the rule no electronic devices?',
'The child should carry a signed letter by the parent/guardian and must submit the device to their respective class teachers and collect it at the end of the day.',
'Does a health check up take place every year?',
'Yes, a health check up is conducted once a year.',
'Is there a school counselor?',
'Yes there is a school counselor, you can get in touch with her during school hours.',
'Do the teachers prepare the students for competitive exams?',
'They are mainly focused in training the students for boards but are always open to doubt clearing.',
'Is there career counseling?',
'Yes, many recognized institutions conduct workshops to help children understand what they want',

])


###request = st.text_input("you:",key=1)
###response = chatbot.get_response(request)
###st.markdown('Bot:'+str(response))



###request = st.text_input("you:",key=2)
###response = chatbot.get_response(request)
###st.markdown('Bot:'+str(response))


send = Button(root, text="Send", font=FONT_BOLD, bg=BG_GRAY,command=send).grid(row=2, column=1)

root.mainloop()


